<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

### Exercise 1 

|**Term**|**Brief Description**|
|:---|:---|
|Subsetting |It is selecting a specific data or a few data points from a list/array. It includes indexing and slicing. |
|Indexing |It is selecting a specific data point. Forward indexing and reverse indexing are types of indexing that can be done. |
|Slicing |It is the selection of a few data points. |
|Masking |After slicing, the data set generated can be masked to create a new data set. |

### Exercise 2

In [2]:
import numpy as np

In [3]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [12]:
np_array = np_array_2d[:, 0]   # selecting all the first elements 
np_array

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [15]:
arr = np_array.astype(int)    # astype() is used to change the type of data
arr                           # change the data from string to integer

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [16]:
mask_division = arr%2        # finding the remainder and creating a new mask 
mask_division                # this mask contains the data of remainders

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [25]:
odd_numbers = mask_division == 1    # checking if the remainder is 0 
odd_numbers                         # create another mask to contain the data set of "true"s and "false"s

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [26]:
result = np_array_2d[odd_numbers, 1]  # from the original array, extract the letters associated with the odd numbers
result 

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')