<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

subseting is selecting data in the list/array. types of subsetting includes indexing and slicing. indexing is subsetting individual data while slicing is selecting a portion of the data. 

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [2]:
import numpy as np 

In [3]:
py_list = ['a1', 'b2', 'c3', 'd4', 'e5', 'f6', 'g7', 'h8', 'i9', 'j10']
np_array = np.array(py_list)
x = np_array 

In [4]:
x[0]

'a1'

In [5]:
x[-1]

'j10'

In [6]:
x[0:3] # indexes the first second and third one, does not include the one where index=3

array(['a1', 'b2', 'c3'], dtype='<U3')

In [7]:
x[1:6]

array(['b2', 'c3', 'd4', 'e5', 'f6'], dtype='<U3')

In [8]:
x[1:6:2]

array(['b2', 'd4', 'f6'], dtype='<U3')

In [9]:
x[:5] # same as the one below 

array(['a1', 'b2', 'c3', 'd4', 'e5'], dtype='<U3')

In [10]:
x[0:5]

array(['a1', 'b2', 'c3', 'd4', 'e5'], dtype='<U3')

In [11]:
x[5:]

array(['f6', 'g7', 'h8', 'i9', 'j10'], dtype='<U3')

In [12]:
x[5:2:-1] # the -1 in this case means in reverse

array(['f6', 'e5', 'd4'], dtype='<U3')

In [13]:
x[::-1]

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

## 1.2 Arrays only | Subsetting by masking

In [18]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask                                               # the my_mask at the end is  telling it to print out my_mask 

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [17]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])   # nothing gets printed out
my_mask = np_array > 3

In [20]:
np_array[my_mask]  #asking it true or false allows you to select out those that are true

array([ 4,  5,  6,  7,  8,  9, 10])

In [21]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [36]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [37]:
np_array[~(np_array) > 3]   # ~ is NOT 

array([], dtype=int64)

In [35]:
np_array[(np_array > 3) & (np_array < 8)]

array([4, 5, 6, 7])

In [33]:
np_array[(np_array < 3) | (np_array > 8)]   # in the array, print out the stuff that is <3 or >8  

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [38]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [40]:
py_list_2d[3]

[4, 'D']

In [41]:
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

In [42]:
py_list_2d[3][0]

4

In [43]:
np_array_2d[3][0]

'4'

In [44]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [45]:
np_array_2d[:3][0]

array(['1', 'A'], dtype='<U21')

In [46]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U21')

In [47]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U21')

In [48]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [53]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [54]:
x=[1]
x=x+[2]
x=x+[3]
x=x+[4]
x

[1, 2, 3, 4]

In [55]:
x=[1]
x+=[2]
x+=[3]
x+=[4]
x

[1, 2, 3, 4]

In [56]:
x=[1]       # append runs the fastest, can compare via the %%timeit 
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [50]:
x = [1, 2, 3]
x+= [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [51]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [52]:
x=[1, 2, 3]         # list within a list
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [57]:
a = (1, 2, 3)

In [58]:
print(a[0])

1


In [59]:
a[0]=-1     # cannot alter data in a tuple
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [60]:
# DONT DO THIS 
x = [1, 2, 3]
y=x
z=x

In [61]:
# the correct way 
x = [1, 2, 3]
y = x.copy()
z = x.copy()

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes