<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [1]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [4]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"] # Python Lists
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [5]:
np_super_names = np.array(["Balck Widow", "Iron Man", "Doctor Strange"]) # Numpy arrays 
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [6]:
superhero_info = { # Dictionary, allows you to hold two sets of info in one structure, unlike an array 
    "Natasha Romanoff": "Black Widow", 
    "Tony Stark": "Iron Man", 
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [7]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"] # Python Lists
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [8]:
py_real_names[0]

'Natasha Romanoff'

In [9]:
py_super_names[0]

'Black Widow'

In [12]:
py_super_names[2] #forward indexing, need to know the size of the list for it to work

'Doctor Strange'

In [14]:
py_super_names[-1] #reverse indexing

'Doctor Strange'

In [15]:
py_super_names[-2]

'Iron Man'

## 1.3 Accessing data from a dictionary

In [16]:
superhero_info = {
    "Natasha Romanoff": "Black Widow", 
    "Tony Stark": "Iron Man", 
    "Stephen Strange": "Doctor Strange"
}

In [17]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [18]:
superhero_info.keys() # access all the keys aka the first value 

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [19]:
superhero_info.values() # access all the values aka the second value 

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [20]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'], 
                    ['Tony Stark', 'Iron Man'], 
                    ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [22]:
py_list_2d = [[1, 'A'], [2, 'B'], [3, 'C'], [4, 'D'], 
             [5, 'E'], [6, 'F'], [7, 'G'], [8, 'H'], 
             [9, 'I'], [10, 'J']]

np_array_2d = np.array(py_list_2d) # reusing the Python list to create a new np array 

In [25]:
len(py_list_2d) # to find how many items are in the list/array 

10

In [26]:
len(np_array_2d)

10

In [27]:
np_array_2d.shape #shape is not a function, thus no (), it is a property attributed to np 

(10, 2)

## 2.2 Arrays are fussy about type

In [28]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [29]:
py_list

[1, 1.5, 'A']

In [30]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [31]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [32]:
py_list + 10

TypeError: can only concatenate list (not "int") to list

In [34]:
np_array + 10

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [36]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [37]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [38]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [39]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [40]:
py_list * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [41]:
np_array * 2 

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [43]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [44]:
py_list **2 

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [45]:
np_array ** 2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [46]:
py_list == 3 #but what exactly are you asking 

False

In [48]:
np_array == 3

array([False, False,  True, False, False])

In [49]:
py_list > 3

TypeError: '>' not supported between instances of 'list' and 'int'

In [50]:
np_array > 3

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [51]:
sum(py_list)

15

In [52]:
np_array.sum()

15

In [53]:
max(py_list)

5

In [54]:
np_array.max()

5

In [55]:
min(py_list)

1

In [56]:
np_array.min()

1

In [57]:
py_list.sum()

AttributeError: 'list' object has no attribute 'sum'

In [58]:
np_array.mean()

3.0

In [59]:
np_array.std()

1.4142135623730951

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes